name: PlatformIO CI

on: 
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      working-directory: ./embeddedctf
      run: pio run -e nodemcuv2_flags -e nodemcuv2_flagless

    - name: Rename flag bin file
      run: mv embeddedctf/.pio/build/nodemcuv2_flags/firmware.bin embeddedctf/.pio/build/nodemcuv2_flags_firmware.bin

    - name: Rename flagless bin file
      run: mv embeddedctf/.pio/build/nodemcuv2_flagless/firmware.bin embeddedctf/.pio/build/nodemcuv2_flagless_firmware.bin

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          embeddedctf/.pio/build/nodemcuv2_flags_firmware.bin
          embeddedctf/.pio/build/nodemcuv2_flagless_firmware.bin
